config/routes.rb
Rails.application.routes.draw do
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get "siberiano", to: "home#siberiano"
  get "golden_retriever", to: "home#golden_retriever"
  get "poodoole", to: "home#poodoole"
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true
    validates :last_name, presence: true
    validates :age, presence: true   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end

    def siberiano
    end

    def golden_retriver
    end

    def poodoole
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all #select * from user;
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit  #get /users/:id/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :last_name, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/golden_retriever.html.erb
<div class="container">
    <h1>
    Golden Retriever
    </h1>
    
    <p>
        Famoso por su pelaje dorado y brillante de longitud media, este Retriever grande tiene una expresión amistosa y una simetría perfecta. Se desplaza con un pasos largos y fuertes en un movimiento fluido y soberbio. Los machos adultos miden entre 56 y 61 cm y pesan de 30 a 34 kg. Las hembras adultas miden entre 51 y 56 cm y pesan de 27 a 32 kg.
    </p>
    
    <%= image_tag("golden.jpg", :alt => "perrito-golden-retriever") %>


</div>

app/views/home/index.html.erb
<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag("perrito2.jpg",  class: "d-block w-100") %>
    </div>
    <div class="carousel-item">
      <%= image_tag("perrito3.jpg",  class: "d-block w-100") %>
    </div>
    <div class="carousel-item">
      <%= image_tag("perrito4.jpg",  class: "d-block w-100") %>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/home/poodoole.html.erb
<div class="container">
  <h1>poodle</h1>
  <p>
    Los poodle son originarios de Alemania y comenzaron siendo perros de caza.
    Sí, con su rápida inteligencia y ganas de complacer, derivaron de perros que
    viajaban con tropas y circos. Gracias a la aristocracia en Francia, lograron
    verlos como perros elegantes y fáciles de amar. Son razas con clase y con
    una personalidad encantadora. Está raza se caracteriza mucho por participar
    en concursos de belleza e incluso por concursos de obstáculos por lo rápidos
    y ágiles que son.
  </p>
  <%= image_tag("po.jpg", :alt => "perrito-poodle") %>
</div>

app/views/home/siberiano.html.erb
<div class="container">
    <h1>
        Husky siberiano
    </h1>
    
    <p>
        El husky siberiano es una raza de perro de trabajo originaria del norte de Siberia (Chukotka, Rusia).
    
        Este perro fue creado por la tribu Chukchi como perro de trabajo para tirar de los trineos a través de largas distancias durante sus partidas de caza, sirviendo, así como vehículo de transporte rápido para las presas de la vuelta al poblado.
        
        Al contrario de lo que narra la creencia popular,[¿cuál?] esta raza jamás tuvo una función de perro pastor ya que el pueblo Chukchi, originalmente, no mantenía ganado propio.
        
        Debido a las condiciones climáticas de sus tierras natales, su pelaje no solo les servía como protección propia ante tan bajas temperaturas, sino que también les brindó un lugar dentro de las tiendas de la tribu, ayudando a mantener calientes a los niños durante la noche. Por ello, el perro Chukchi (como era conocido originalmente), era muy apreciado también (e incluso gratamente reconocido por otras tribus), por su aportación al núcleo familiar, a pesar de ser realmente un perro de trabajo activo. 
    </p>
    
    <%= image_tag("siberiano.jpg", :alt => "perrito-siberiano") %>


</div>

app/views/layouts/_navbar.html.erb
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "home", root_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "siberiano", siberiano_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "golden retriever", golden_retriever_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "poodle", poodoole_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "users", users_path, class: "nav-link" %>
      </li>

        
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ViewPeople</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css" integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <%= favicon_link_tag asset_path('perrito.png') %>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= user.last_name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= user.age %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<div class="container">
  <p style="color: rgb(9, 192, 9)"><%= notice %></p>
  <h1 class="text-center">Users</h1>
  <div id="users">
    <%# @users.each do |user| %> <%#= render user %>
    <p><%#= link_to "Show this user", user, class: "btn btn-warning" %></p>
    <%# end %>
  </div>
</div>
<%= link_to "New user", new_user_path, class: "btn btn-success" %>
<div class="container">
  <div class="card" style="width: 18rem">
    <% @users.each do |user| %>
    <div class="card-body">
      <%= image_tag("incognita.jpeg", :alt => "incognita") %>
      <h5 class="card-title">Nombre: <%= user.name %> <%= user.last_name %></h5>
      <p class="card-text">Edad: <%= user.age %></p>
      <%= link_to "Mostrar usuario", user, class: "btn btn-warning" %>
    </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<div class="container">
  
  <p style="color: green"><%= notice %></p>
  
  <%= render @user %>
  
  <div>
    <%= link_to "Editar usuario", edit_user_path(@user), class: "btn btn-info" %> |
    <%= link_to "Volver a usuarios", users_path, class: "btn btn-info" %>
  
    <%= button_to "Eliminar usuario", @user, method: :delete, class: "btn btn-danger" %>
  </div>


</div>